1. Get used to two basic workhorse data structures: `Series` and `DataFrame`.

In [2]:
import pandas as pd
from pandas import DataFrame,Series
import numpy as np

In [2]:
obj = Series([4,7,-5,3],index=['d','b','a','c'])
obj

d    4
b    7
a   -5
c    3
dtype: int64

In [3]:
obj['a']

-5

In [4]:
obj[['d','b','c']]

d    4
b    7
c    3
dtype: int64

2. Think about a Series as a __fixed-length, ordered dict__, as it is a mapping of index values to data values. It can be used in many contexts where you might use a dict. 
3. You can creat a Series with a dict.

In [5]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

4. Use `isnull()` and `notnull()` to detect the NA.

In [6]:
obj4 = pd.Series(sdata,index=['California','Ohio','Oregon','Texas'])
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [7]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [8]:
obj4.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [10]:
obj4.name='population'
obj4.index.name='state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [11]:
obj

d    4
b    7
a   -5
c    3
dtype: int64

In [12]:
obj.index=['Bob','Steve','Jeff','Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

5. DataFrame can be thought of as a __dict of Series all sharing the same index__.

6. The most common way to creat a DataFrame is __from a dict of equal-length list or NumPy arrays__.

In [15]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
       'year':[2000,2001,2002,2001,2002,2003],
       'pop':[1.5,1.7,3.6,2.4,2.,3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.0
5  Nevada  2003  3.2

7. If you specify a sequence of columns, the DataFrame's columns will be arranged in that order

In [16]:
pd.DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.0
5  2003  Nevada  3.2

In [18]:
frame2 = pd.DataFrame(data,columns=['year','state','pop','debt'])
frame2

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.0  NaN
5  2003  Nevada  3.2  NaN

In [19]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

8. A column in DataFrame can be retrieved as a Series ether by dict-like notation or by attribute. __Please use dict-like notation!__

In [22]:
frame2['year']

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [23]:
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [26]:
frame2['eastern'] = frame2['state']=='Ohio'
frame2

year   state  pop debt  eastern
0  2000    Ohio  1.5  NaN     True
1  2001    Ohio  1.7  NaN     True
2  2002    Ohio  3.6  NaN     True
3  2001  Nevada  2.4  NaN    False
4  2002  Nevada  2.0  NaN    False
5  2003  Nevada  3.2  NaN    False

In [27]:
del frame2['eastern']
frame2

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.0  NaN
5  2003  Nevada  3.2  NaN

In [3]:
pop = {'Nevada':{2001:2.4,2002:2.9},
      'Ohio':{2000:2.5,2001:1.7,2002:3.6}}
frame3 = DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   2.5

In [4]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   2.5

In [6]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 2.5]])

# Index Objects

In [7]:
obj = pd.Series(range(3),index=['a','b','c'])
index = obj.index

In [8]:
index

Index(['a', 'b', 'c'], dtype='object')

In [9]:
index[1]

'b'

9. You can creat an `Index` object on your own.

In [10]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [11]:
obj2 = Series([1,2,3],index=labels)

In [12]:
obj2

0    1
1    2
2    3
dtype: int64

In [13]:
obj2.index is labels

True

# Essential Functionality

- Reindexing
- Dropping Entries from an Axis. `obj.drop(['a','b'])`, will always return a new object.
    - For Series, `obj.drop()` is nothing special.
    - For DataFrame, if you want to drop rows: `frame.drop(['row1','row2'])`; if you want to drop columns:` frame.drop(['column1','column2'],axis=1)`
    - Include `inplace=True` without returning a new object.

- Indexing,Selection and Filtering
    - __Slicing with _labels_ behaves differently than normal Python slicing in that the endpoint is inclusive!__
    - Use `loc` and `iloc` to select a subset of rows and columns from a DataFrame with Numpy-like notation using either labels(`loc`) or integers(`iloc`).
    - When a Series or DataFrame is indexed with integers,  data selection will always be label-oriented.
    ```python
    ser2 = pd.Series(np.arange(3))
    ser2
#     0    0
#     1    1
#     2    2
#     dtype: int64
    
    ```
    `ser2[-1]` doesn't make sense, because `-1` is not a leble. To avoid misunderstanding, Using `loc` or `iloc` helps.

In [14]:
obj = pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [16]:
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [17]:
obj3 = pd.Series(['blue','purple','yello'],index=[0,2,4])
obj3

0      blue
2    purple
4     yello
dtype: object

In [19]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4     yello
5     yello
dtype: object

In [24]:
frame = DataFrame(np.arange(9).reshape((3,3)),
                 index=['a','c','d'],
                 columns=['Ohio','Texas','California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [25]:
frame.reindex(['a','b','c','d'])

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [26]:
frame.reindex(columns=['Texas','Utah','California'])

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [27]:
obj = pd.Series(np.arange(5),index=['a','b','c','d','e'])
obj

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [28]:
new_obj = obj.drop('c')
new_obj

a    0
b    1
d    3
e    4
dtype: int64

In [31]:
new_obj = obj.drop(['b','d'])
new_obj

a    0
c    2
e    4
dtype: int64

In [32]:
data = DataFrame(np.arange(16).reshape((4,4)),
                 index=['Ohio','Coorado','Utah','New York'],
                 columns = ['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Coorado     4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [33]:
data.drop(['Coorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [35]:
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Coorado     4      6     7
Utah        8     10    11
New York   12     14    15

In [37]:
data.loc['Coorado',['two','three']]

two      5
three    6
Name: Coorado, dtype: int64

In [39]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [40]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [41]:
data

one  two  three  four
Ohio        0    1      2     3
Coorado     4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [43]:
ser2 = pd.Series(np.arange(3))
ser2

0    0
1    1
2    2
dtype: int64

# Arithmetic methods with fill values
- Operations between DataFrame and Series.

In [51]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
arr-arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [54]:
frame = pd.DataFrame(np.arange(12).reshape((4,3)),
                     columns = list('bde'),
                     index = ['Utah','Ohio','Texas','Oregon'])
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [56]:
series = frame.iloc[0]
series

b    0
d    1
e    2
Name: Utah, dtype: int64

In [57]:
frame-series

b  d  e
Utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregon  9  9  9

In [58]:
series2 = Series(range(3),index=('b','e','f'))
series2

b    0
e    1
f    2
dtype: int64

In [59]:
frame-series2

b   d     e   f
Utah    0.0 NaN   1.0 NaN
Ohio    3.0 NaN   4.0 NaN
Texas   6.0 NaN   7.0 NaN
Oregon  9.0 NaN  10.0 NaN

In [44]:
df1 = DataFrame(np.arange(12).reshape((3,4)),
                columns = list('abcd'))
df2 = DataFrame(np.arange(20).reshape((4,5)),
                columns = list('abcde'))
df2.loc[1,'b']=np.nan

In [45]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [46]:
df2

a     b   c   d   e
0   0   1.0   2   3   4
1   5   NaN   7   8   9
2  10  11.0  12  13  14
3  15  16.0  17  18  19

In [47]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [48]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [49]:
df1.rsub(df2,fill_value=0)

a     b     c     d     e
0   0.0   0.0   0.0   0.0   4.0
1   1.0  -5.0   1.0   1.0   9.0
2   2.0   2.0   2.0   2.0  14.0
3  15.0  16.0  17.0  18.0  19.0

# Function Application and Mapping
- Numpy ufuncs(element-wise array method) also work with pandas objecs.
- Use `.apply(func,axis=)` to apply a function to two rows or columns.
- Use `.applymap(func)` to apply a element-wise function to elements in a DataFrame; Use `.map(func)` to apply a alement-wise function to elements in a Series.

In [61]:
frame = pd.DataFrame(np.random.randn(4,3),columns=list('bde'),
                      index=['Utah','Ohio','Texas','Oregon'])
frame

b         d         e
Utah   -0.041693  1.542017  1.448887
Ohio    0.074297 -0.197213  1.993275
Texas  -0.803328  0.014455 -0.077905
Oregon -0.074639 -0.918863  2.061493

In [62]:
np.abs(frame)

b         d         e
Utah    0.041693  1.542017  1.448887
Ohio    0.074297  0.197213  1.993275
Texas   0.803328  0.014455  0.077905
Oregon  0.074639  0.918863  2.061493

In [65]:
fun = lambda x:x.max()-x.min()
frame.apply(fun,axis=0)

b    0.877625
d    2.460880
e    2.139399
dtype: float64

In [64]:
frame.apply(fun,axis=1)

Utah      1.583710
Ohio      2.190488
Texas     0.817783
Oregon    2.980356
dtype: float64

In [66]:
def f(x):
    return Series([x.min(),x.max()],index=['min','max'])

In [68]:
frame.apply(f,axis=1)

min       max
Utah   -0.041693  1.542017
Ohio   -0.197213  1.993275
Texas  -0.803328  0.014455
Oregon -0.918863  2.061493

In [69]:
frame

b         d         e
Utah   -0.041693  1.542017  1.448887
Ohio    0.074297 -0.197213  1.993275
Texas  -0.803328  0.014455 -0.077905
Oregon -0.074639 -0.918863  2.061493

In [73]:
fo = lambda x: '%.2f' % x

In [74]:
frame.applymap(fo)

b      d      e
Utah    -0.04   1.54   1.45
Ohio     0.07  -0.20   1.99
Texas   -0.80   0.01  -0.08
Oregon  -0.07  -0.92   2.06

# Sorting and Ranking
- Sorting
    - `.sort_index(axis=)`
    - `.sort_values(axis=)`. For DataFrame, pass the column name to `by` option.
- Ranking
    - `.rank()`.

In [75]:
obj = DataFrame(range(4),index=['d','a','b','c'])
obj

0
d  0
a  1
b  2
c  3

In [76]:
obj.sort_index()

0
a  1
b  2
c  3
d  0

In [78]:
frame = DataFrame(np.arange(8).reshape((2,4)),
                  index=['three','one'],
                  columns = list('dabc'))
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [80]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [81]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [82]:
frame.sort_index(axis=1,ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [83]:
obj = Series([4,7,-3,2])
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [85]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [86]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [87]:
frame = DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [90]:
frame.sort_values(axis=0,by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [91]:
obj = pd.Series([7,-5,7,4,2,0,4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [92]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [93]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

# Summarizing and Computing Descriptive Statics

In [94]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
 [np.nan, np.nan], [0.75, -1.3]],
index=['a', 'b', 'c', 'd'],
columns=['one', 'two'])

In [95]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [96]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [97]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [98]:
df.mean(axis=1,skipna=True)

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [99]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [100]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [101]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [107]:
import pandas_datareader.data as web
df = web.DataReader('GE', 'yahoo', start='2019-09-10', end='2019-10-09')

ProxyError: HTTPSConnectionPool(host='finance.yahoo.com', port=443): Max retries exceeded with url: /quote/GE/history?period1=1568059200&period2=1570651199&interval=1d&frequency=1d&filter=history (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer')))

In [ ]:
df